version: "3"

services:
  redis:
    image: redis:7.0.5
    container_name: neko-transaction-redis
    networks:
      - neko_transaction
    depends_on:
      - nacos
    restart: always

  mysql-service:
    image: registry.cn-shanghai.aliyuncs.com/neko_dev/neko_transaction_mysql:1.0
    container_name: neko-transaction-mysql
    ports:
      - "3306:3306"
    volumes:
      - /neko_transaction/mysql/data:/var/lib/mysql
    networks:
      - neko_transaction
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: no
    restart: always

  rabbitmq:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-rabbitmq:1.0
    container_name: neko-transaction-rabbitmq
    networks:
      - neko_transaction
    depends_on:
      - redis
    restart: always

  elasticsearch:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-elasticsearch:1.0
    container_name: neko-transaction-elasticsearch
    networks:
      - neko_transaction
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx512m
      - discovery.type=single-node
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always

  nginx:
    image: registry.cn-shanghai.aliyuncs.com/neko_dev/neko-transaction-nginx:1.0
    container_name: neko-transaction-nginx
    ports:
      - "80:80"
      - "81:81"
    networks:
      - neko_transaction
    depends_on:
      - gateway-service
    environment:
      BACKEND_URL: http://192.168.30.133:8004/
    command: /bin/bash -c "/init_backend_url.sh && /init_admin_backend_url.sh && /docker-entrypoint.sh nginx -g 'daemon off;'"
    restart: always

  nacos:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-nacos:1.0
    container_name: neko-transaction-nacos
    ports:
      - "8848:8848"
    networks:
      - neko_transaction
    depends_on:
      - mysql-service
    environment:
      MYSQL_URL: jdbc:mysql://mysql-service:3306/nacos_config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8848/nacos" ]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: always

  seata:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-seata:1.0
    container_name: neko-transaction-seata
    ports:
      - "8091:8091"
      - "7091:7091"
    networks:
      - neko_transaction
    depends_on:
      - nacos
    environment:
      SEATA_IP: 192.168.30.133
      SEATA_PORT: 8091
      SEATA_USER_NAME: seata
      SEATA_PASSWORD: seata
      NACOS_SERVER_ADDR: 192.168.30.133:8848
      NACOS_NAME_SPACE: 3de83da7-02c3-46e1-8c59-930031b9c30b
      NACOS_CONFIG_GROUP: NEKO-TRANSACTION-SEATA
      NACOS_REGISTRY_GROUP: NEKO-TRANSACTION
      NACOS_USER_NAME: nacos
      NACOS_PASSWORD: nacos
      NACOS_CONFIG_DATA_ID: neko-transaction-seata-server.properties
      NACOS_REGISTRY_NAME: neko-transaction-seata-server
      NACOS_REGISTRY_CLUSTER: default
      MYSQL_URL: jdbc:mysql://192.168.30.133:3306/neko_transaction_seata?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&autoReConnect=true
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
      DEFAULT_TX_GROUP: default
      SERVICE_GROUP_LIST: 192.168.30.133:8091
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7091" ]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: always

  gateway-service:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-backend:jre17
    container_name: neko-transaction-gateway
    ports:
      - "8004:8004"
    volumes:
      - /neko_transaction/gateway/app:/app
    networks:
      - neko_transaction
    depends_on:
      - seata
      - elasticsearch
    environment:
      NACOS_SERVER_ADDR: nacos:8848
      SENTINEL_DASHBOARD_URL: 192.168.30.133:8080
      SENTINEL_PORT: 8719
      PROFILES_ACTIVE: prop
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8004" ]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always

  member-service:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-backend:jre17
    container_name: neko-transaction-member
    ports:
      - "8003:8003"
    volumes:
      - /neko_transaction/member/app:/app
    networks:
      - neko_transaction
    depends_on:
      - mysql-service
      - nacos
      - redis
      - rabbitmq
      - gateway-service
    environment:
      NACOS_SERVER_ADDR: nacos:8848
      SENTINEL_DASHBOARD_URL: 192.168.30.133:8080
      SENTINEL_PORT: 8719
      MYSQL_URL: jdbc:mysql://mysql-service:3306/neko_transaction_member?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&autoReConnect=true
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      PROFILES_ACTIVE: prop
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8003" ]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always

  product-service:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-backend:jre17
    container_name: neko-transaction-product
    ports:
      - "8005:8005"
    volumes:
      - /neko_transaction/product/app:/app
    networks:
      - neko_transaction
    depends_on:
      - mysql-service
      - nacos
      - redis
      - rabbitmq
      - elasticsearch
      - member-service
    environment:
      NACOS_SERVER_ADDR: nacos:8848
      SENTINEL_DASHBOARD_URL: 192.168.30.133:8080
      SENTINEL_PORT: 8719
      MYSQL_URL: jdbc:mysql://mysql-service:3306/neko_transaction_product?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&autoReConnect=true
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      ELASTIC_SEARCH_HOSTS: elasticsearch:9200
      PROFILES_ACTIVE: prop
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8005" ]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always

  ware-service:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-backend:jre17
    container_name: neko-transaction-ware
    ports:
      - "8007:8007"
    volumes:
      - /neko_transaction/ware/app:/app
    networks:
      - neko_transaction
    depends_on:
      - mysql-service
      - nacos
      - redis
      - rabbitmq
      - product-service
    environment:
      NACOS_SERVER_ADDR: nacos:8848
      SENTINEL_DASHBOARD_URL: 192.168.30.133:8080
      SENTINEL_PORT: 8719
      MYSQL_URL: jdbc:mysql://mysql-service:3306/neko_transaction_ware?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&autoReConnect=true
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      PROFILES_ACTIVE: prop
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8007" ]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always

  third-party-service:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-backend:jre17
    container_name: neko-transaction-third-party
    ports:
      - "8006:8006"
    volumes:
      - /neko_transaction/third_party/app:/app
    networks:
      - neko_transaction
    depends_on:
      - mysql-service
      - nacos
      - redis
      - ware-service
    environment:
      NACOS_SERVER_ADDR: nacos:8848
      SENTINEL_DASHBOARD_URL: 192.168.30.133:8080
      SENTINEL_PORT: 8719
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PROFILES_ACTIVE: prop
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8006" ]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always

networks:
  neko_transaction:
