version: "3"

services:
  redis:
    image: redis:7.0.5
    container_name: neko-transaction-redis
    networks:
      - neko_transaction
    depends_on:
      - nacos
    restart: always

  mysql:
    image: registry.cn-shanghai.aliyuncs.com/neko_dev/neko_transaction_mysql:1.0
    container_name: neko-transaction-mysql
    ports:
      - "3306:3306"
    volumes:
      - /neko_transaction/mysql/data:/var/lib/mysql
    networks:
      - neko_transaction
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: no
    restart: always

  rabbitmq:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-rabbitmq:1.0
    container_name: neko-transaction-rabbitmq
    networks:
      - neko_transaction
    depends_on:
      - redis
    restart: always

  elasticsearch:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-elasticsearch:1.0
    container_name: neko-transaction-elasticsearch
    networks:
      - neko_transaction
    depends_on:
      - rabbitmq
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx512m
      - discovery.type=single-node
    restart: always

  nginx:
    image: neko-transaction-nginx:1.0
    container_name: neko-transaction-nginx
    ports:
      - "80:80"
      - "81:81"
    networks:
      - neko_transaction
    depends_on:
      - gateway-service
    restart: always

  nacos:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-nacos:1.0
    container_name: neko-transaction-nacos
    ports:
      - "8848:8848"
    networks:
      - neko_transaction
    depends_on:
      - mysql
    environment:
      MYSQL_URL: jdbc:mysql://mysql:3306/nacos_config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
    restart: always

  gateway-service:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-backend:jre17
    container_name: neko-transaction-gateway
    ports:
      - "8004:8004"
    volumes:
      - /neko_transaction/gateway/app:/app
    networks:
      - neko_transaction
    depends_on:
      - nacos
      - elasticsearch
    environment:
      NACOS_SERVER_ADDR: nacos:8848
      SENTINEL_DASHBOARD_URL: 192.168.30.133:8080
      SENTINEL_PORT: 8719
      PROFILES_ACTIVE: prop
    restart: always

  member-service:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-backend:jre17
    container_name: neko-transaction-member
    ports:
      - "8003:8003"
    volumes:
      - /neko_transaction/member/app:/app
    networks:
      - neko_transaction
    depends_on:
      - mysql
      - nacos
      - redis
      - rabbitmq
      - gateway-service
    environment:
      NACOS_SERVER_ADDR: nacos:8848
      SENTINEL_DASHBOARD_URL: 192.168.30.133:8080
      SENTINEL_PORT: 8719
      MYSQL_URL: jdbc:mysql://mysql:3306/neko_transaction_member?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&autoReConnect=true
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      PROFILES_ACTIVE: prop
    restart: always

  product-service:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-backend:jre17
    container_name: neko-transaction-product
    ports:
      - "8005:8005"
    volumes:
      - /neko_transaction/product/app:/app
    networks:
      - neko_transaction
    depends_on:
      - mysql
      - nacos
      - redis
      - rabbitmq
      - elasticsearch
      - member-service
    environment:
      NACOS_SERVER_ADDR: nacos:8848
      SENTINEL_DASHBOARD_URL: 192.168.30.133:8080
      SENTINEL_PORT: 8719
      MYSQL_URL: jdbc:mysql://mysql:3306/neko_transaction_product?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&autoReConnect=true
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      ELASTIC_SEARCH_HOSTS: elasticsearch:9200
      PROFILES_ACTIVE: prop
    restart: always

  ware-service:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-backend:jre17
    container_name: neko-transaction-ware
    ports:
      - "8007:8007"
    volumes:
      - /neko_transaction/ware/app:/app
    networks:
      - neko_transaction
    depends_on:
      - mysql
      - nacos
      - redis
      - rabbitmq
      - product-service
    environment:
      NACOS_SERVER_ADDR: nacos:8848
      SENTINEL_DASHBOARD_URL: 192.168.30.133:8080
      SENTINEL_PORT: 8719
      MYSQL_URL: jdbc:mysql://mysql:3306/neko_transaction_ware?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&autoReConnect=true
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      PROFILES_ACTIVE: prop
    restart: always

  third-party-service:
    image: registry.cn-shanghai.aliyuncs.com/neko_base/neko-backend:jre17
    container_name: neko-transaction-third-party
    ports:
      - "8006:8006"
    volumes:
      - /neko_transaction/third_party/app:/app
    networks:
      - neko_transaction
    depends_on:
      - mysql
      - nacos
      - redis
      - ware-service
    environment:
      NACOS_SERVER_ADDR: nacos:8848
      SENTINEL_DASHBOARD_URL: 192.168.30.133:8080
      SENTINEL_PORT: 8719
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PROFILES_ACTIVE: prop
    restart: always

networks:
  neko_transaction:
